version: "3"
services:
  umbrel:
    image: dockur/umbrel:latest
    container_name: umbrel
    network_mode: bridge
    ports:
      - 7080:80 # Acesse via http://IP-DO-SERVIDOR:8080
    volumes:
      - /home/portainer/umbrel:/data # Altere para uma pasta real no seu servidor
    environment:
      - NGINX_PORT=80
    restart: always
    stop_grace_period: 1m
