version: "3.7"

services:
  umbrel:
    build: .
    container_name: umbrel
    restart: always
    ports:
      - "7081:80"
      - "7444:443"
    volumes:
      - ./umbrel-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
